In [1]:
import pandas as pd
import sys
import os
from dotenv import load_dotenv

sys.path.append(os.path.abspath('..'))
from helpers import RAND_STATE
from helpers import feature_eng_helpers as fp

IMPORTING DATA

In [2]:
load_dotenv()
train0 = pd.read_csv(os.getenv("CLEAN_DATA_PATH") + "/" + "sales_train_cnt_0.csv")

In [3]:
items = pd.read_csv(os.getenv("ORIGINAL_DATA_PATH") + "/" + "items.csv")

In [4]:
submit_ids = pd.read_csv(os.getenv("ORIGINAL_DATA_PATH") + "/" + "test.csv")

In [5]:
train_sub = submit_ids[["shop_id", "item_id"]]
train_sub["month_block_num"] = 34

In [6]:
train_sub.head()

   shop_id  item_id  month_block_num
0        5     5037               34
1        5     5320               34
2        5     5233               34
3        5     5232               34
4        5     5268               34

In [7]:
processed_train = fp.get_preprocessed_data(train0.copy())

In [8]:
processed_train.head()

,item_id,shop_id,month_block_num,item_name_length,num_months_sold_prior,avg_sales_per_shop,avg_sales_per_item,avg_item_price_per_month,avg_shop_price_per_month,item_price_median,item_cnt_month
0,100,14,2,25,0,1789.000000,0.000000,134.400,651.064638,149.0,1.0
1,100,19,3,25,1,2976.333333,5.000000,139.875,615.435495,149.0,1.0
2,100,19,5,25,3,2663.200000,6.666667,149.000,644.135200,149.0,1.0
3,100,19,10,25,8,2642.400000,5.375000,149.000,720.168373,149.0,1.0
4,100,21,2,25,0,1676.000000,0.000000,134.400,637.878276,149.0,1.0

In [10]:
train_sub = fp.add_features_to_sub_df(train_sub, processed_train)

In [15]:
train_sub.head()

  shop_id item_id  month_block_num  item_cnt_month  item_price_median
0       5    5037               34             0.0                0.0
1       5   other               34           248.0              449.0
2       5    5233               34             1.0             1199.0
3       5    5232               34             0.0                0.0
4       5   other               34           248.0              449.0

In [16]:
train_sub.to_csv(os.getenv("SUBMISSION_DATA_PATH") + "/" + "train_submission.csv", index=False)