In [1]:
import pandas as pd
from dotenv import load_dotenv
import os

Importing and Viewing Data

In [2]:
load_dotenv()
training_data = pd.read_csv(os.getenv('ORIGINAL_DATA_PATH') + '/sales_train.csv')
items_data = pd.read_csv(os.getenv('ORIGINAL_DATA_PATH') + '/items.csv')
shops_data = pd.read_csv(os.getenv('ORIGINAL_DATA_PATH') + '/shops.csv')
test_data = pd.read_csv(os.getenv('ORIGINAL_DATA_PATH') + '/test.csv')
items_categories_data = pd.read_csv(os.getenv('ORIGINAL_DATA_PATH') + '/item_categories.csv')

In [ ]:
def get_df_col_and_datatypes(df: pd.DataFrame):
    """
    This function performs a preliminary data analysis on a given DataFrame.
    It prints the shape, columns, types, description, missing values, and unique values of the DataFrame.
    """
    print(f"columns: \n {df.columns.tolist()}")
    print(f"types: \n {df.dtypes}")

Viewing Dataframe Forms

In [15]:
get_df_col_and_datatypes(training_data)
training_data.head(7)

columns:
 ['date', 'date_block_num', 'shop_id', 'item_id', 'item_price', 'item_cnt_day']
types:
 date                  str
date_block_num      int64
shop_id             int64
item_id             int64
item_price        float64
item_cnt_day      float64
dtype: object
missing values:
 date              0
date_block_num    0
shop_id           0
item_id           0
item_price        0
item_cnt_day      0
dtype: int64

         date  date_block_num  shop_id  item_id  item_price  item_cnt_day
0  02.01.2013               0       59    22154      999.00           1.0
1  03.01.2013               0       25     2552      899.00           1.0
2  05.01.2013               0       25     2552      899.00          -1.0
3  06.01.2013               0       25     2554     1709.05           1.0
4  15.01.2013               0       25     2555     1099.00           1.0
5  10.01.2013               0       25     2564      349.00           1.0
6  02.01.2013               0       25     2565      549.00           1.0

In [17]:
get_df_col_and_datatypes(items_data)
items_data.head(7)

columns:
 ['item_name', 'item_id', 'item_category_id']
types:
 item_name             str
item_id             int64
item_category_id    int64
dtype: object
missing values:
 item_name           0
item_id             0
item_category_id    0
dtype: int64

,item_name,item_id,item_category_id
0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,0,40
1,!ABBYY FineReader 12 Professional Edition Full...,1,76
2,***В ЛУЧАХ СЛАВЫ (UNV) D,2,40
3,***ГОЛУБАЯ ВОЛНА (Univ) D,3,40
4,***КОРОБКА (СТЕКЛО) D,4,40
5,***НОВЫЕ АМЕРИКАНСКИЕ ГРАФФИТИ (UNI) ...,5,40
6,***УДАР ПО ВОРОТАМ (UNI) D,6,40

In [18]:
get_df_col_and_datatypes(shops_data)
shops_data.head(7)

columns:
 ['shop_name', 'shop_id']
types:
 shop_name      str
shop_id      int64
dtype: object
missing values:
 shop_name    0
shop_id      0
dtype: int64

                        shop_name  shop_id
0   !Якутск Орджоникидзе, 56 фран        0
1   !Якутск ТЦ "Центральный" фран        1
2                Адыгея ТЦ "Мега"        2
3  Балашиха ТРК "Октябрь-Киномир"        3
4        Волжский ТЦ "Волга Молл"        4
5          Вологда ТРЦ "Мармелад"        5
6      Воронеж (Плехановская, 13)        6

In [19]:
get_df_col_and_datatypes(items_categories_data)
items_categories_data.head(7)

columns:
 ['item_category_name', 'item_category_id']
types:
 item_category_name      str
item_category_id      int64
dtype: object
missing values:
 item_category_name    0
item_category_id      0
dtype: int64

        item_category_name  item_category_id
0  PC - Гарнитуры/Наушники                 0
1         Аксессуары - PS2                 1
2         Аксессуары - PS3                 2
3         Аксессуары - PS4                 3
4         Аксессуары - PSP                 4
5      Аксессуары - PSVita                 5
6    Аксессуары - XBOX 360                 6

In [20]:
get_df_col_and_datatypes(test_data)
test_data.head(7)

columns:
 ['ID', 'shop_id', 'item_id']
types:
 ID         int64
shop_id    int64
item_id    int64
dtype: object
missing values:
 ID         0
shop_id    0
item_id    0
dtype: int64

   ID  shop_id  item_id
0   0        5     5037
1   1        5     5320
2   2        5     5233
3   3        5     5232
4   4        5     5268
5   5        5     5039
6   6        5     5041

In [4]:
# the names of the columns that are id (unique keys) columns
id_cols = ['item_id', 'shop_id', 'item_category_id']

Dataframe Basic Stats

In [ ]:
def get_basic_stats(df: pd.DataFrame):
    """
    This function returns a dictionary of basic statistics for a given DataFrame.
    """
    print(f"shape: {df.shape}")
    non_id_cols = [col for col in df.columns if col not in id_cols]
    #id columns are treated as numerical values
    print(f"dataframe basic continuous statistics \n{df[non_id_cols].describe()}")
    #displays statistics like frequency
    #TODO: move this print function call elsewhere, only necessary for training data
    print(f"dataframe cat statistics \n {df[id_cols].map(lambda x: str(x)).describe()}")

In [26]:

get_basic_stats(training_data)

shape: (2935849, 6)
unique values:
 date               1034
date_block_num       34
shop_id              60
item_id           21807
item_price        19993
item_cnt_day        198
dtype: int64
datafram basic statistics
       date_block_num    item_price  item_cnt_day
count    2.935849e+06  2.935849e+06  2.935849e+06
mean     1.456991e+01  8.908532e+02  1.242641e+00
std      9.422988e+00  1.729800e+03  2.618834e+00
min      0.000000e+00 -1.000000e+00 -2.200000e+01
25%      7.000000e+00  2.490000e+02  1.000000e+00
50%      1.400000e+01  3.990000e+02  1.000000e+00
75%      2.300000e+01  9.990000e+02  1.000000e+00
max      3.300000e+01  3.079800e+05  2.169000e+03

In [7]:
# shows statistics like the number of times shops and items show up in the data
training_data[['item_id', 'shop_id']].map(lambda x: str(x)).describe()

        item_id  shop_id
count   2935849  2935849
unique    21807       60
top       20949       31
freq      31340   235636

In [27]:

get_basic_stats(items_data)

shape: (22170, 3)
unique values:
 item_name           22170
item_id             22170
item_category_id       84
dtype: int64
datafram basic statistics
                                        item_name
count                                       22170
unique                                      22170
top     ! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.)         D
freq                                            1

In [30]:
get_basic_stats(items_categories_data)

shape: (84, 2)
unique values:
 item_category_name    84
item_category_id      84
dtype: int64
datafram basic statistics
             item_category_name
count                        84
unique                       84
top     PC - Гарнитуры/Наушники
freq                          1

In [28]:

get_basic_stats(shops_data)

shape: (60, 2)
unique values:
 shop_name    60
shop_id      60
dtype: int64
datafram basic statistics
                            shop_name
count                              60
unique                             60
top     !Якутск Орджоникидзе, 56 фран
freq                                1

Looking for Data Validity Issues

In [43]:
def check_data_validity(df: pd.DataFrame):
    """
    This function checks the validity of the data in a given DataFrame by checking for missing values and unique values.
    for missing values, duplications and outliers.
    """
    print(f"missing values: \n {df.isnull().sum()}")
    print(f"unique values: \n {df.nunique()}")
    numeric_cols = []
    non_numeric_cols = []
    for col in df.columns:
        # checks if the cloumn contains numeric values and is not an id column
        if (df[col].dtype in ['int64', 'float64']) and (col not in id_cols):
            numeric_cols.append(col)
        else:
            non_numeric_cols.append(col)
    # numerical values in this case are expected to be positive
    invalid_numeric_values = df[numeric_cols].map(lambda x: 1 if x<0 else 0).sum()
    # categorical values in this case are expected to be non-empty strings or numbers
    invalid_cat_values = df[non_numeric_cols].map(lambda x: 1 if ((pd.isna(x)) or (str(x)=='')) else 0).sum()
    print(f"invalid numeric values: \n {invalid_numeric_values}")
    print(f"invalid categorical values: \n {invalid_cat_values}")

In [44]:
check_data_validity(training_data)

missing values:
 date              0
date_block_num    0
shop_id           0
item_id           0
item_price        0
item_cnt_day      0
dtype: int64
unique values:
 date               1034
date_block_num       34
shop_id              60
item_id           21807
item_price        19993
item_cnt_day        198
dtype: int64
invalid numeric values:
 date_block_num       0
item_price           1
item_cnt_day      7356
dtype: int64
invalid categorical values:
 date       0
shop_id    0
item_id    0
dtype: int64

In [39]:
training_data[["item_price", "item_cnt_day"]].map(lambda x: 0 if x<0 else 1).sum()

item_price      2935848
item_cnt_day    2928493
dtype: int64